### ISSUE TITLE
Pyinstaller packaging issues

### ISSUE THREAD

**Issue by matham** [matham/ffpyplayer#1]
When packaging a app that uses ffpyplaer, pyinstaller has issues with loading the internal modules (e.g. ffthreading) when loading e.g. ffpyplayer.player and fails.

The error is:

```
 Traceback (most recent call last):
   File "<string>", line 2, in <module>
   File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
     exec(bytecode, module.__dict__)
   File "C:\Users\.\Documents\Eclipse\Filers\build\filers\out00-PYZ.pyz\filers.main", line 43, in <module>
   File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
     exec(bytecode, module.__dict__)
   File "C:\Users\.\Documents\Eclipse\Filers\build\filers\out00-PYZ.pyz\filers.record", line 36, in <module>
   File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 409, in load_module
     module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
   File "ffthreading.pxd", line 9, in init ffpyplayer.player (ffpyplayer\player.c:7399)
 ImportError: No module named ffthreading
```

Looking at that line in player.c we have:

```
__pyx_ptype_10ffpyplayer_11ffthreading_MTCond = __Pyx_ImportType("ffpyplayer.ffthreading", "MTCond", sizeof(struct __pyx_obj_10ffpyplayer_11ffthreading_MTCond), 1); if (unlikely(!__pyx_ptype_10ffpyplayer_11ffthreading_MTCond)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
```

A way around is to add ffpyplayer in the exclude list, e.g. 

```
a = Analysis([...], excludes=['ffpyplayer'])
```

and manually adding the ffpyplayer directory.

**Comment by tosimplicity** [comment]
> When packaging a app that uses ffpyplaer, pyinstaller has issues with loading the internal modules (e.g. ffthreading) when loading e.g. ffpyplayer.player and fails.
> 
> The error is:
> 
> ```
>  Traceback (most recent call last):
>    File "<string>", line 2, in <module>
>    File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
>      exec(bytecode, module.__dict__)
>    File "C:\Users\.\Documents\Eclipse\Filers\build\filers\out00-PYZ.pyz\filers.main", line 43, in <module>
>    File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
>      exec(bytecode, module.__dict__)
>    File "C:\Users\.\Documents\Eclipse\Filers\build\filers\out00-PYZ.pyz\filers.record", line 36, in <module>
>    File "C:\kivy-build\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 409, in load_module
>      module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
>    File "ffthreading.pxd", line 9, in init ffpyplayer.player (ffpyplayer\player.c:7399)
>  ImportError: No module named ffthreading
> ```
> 
> Looking at that line in player.c we have:
> 
> ```
> __pyx_ptype_10ffpyplayer_11ffthreading_MTCond = __Pyx_ImportType("ffpyplayer.ffthreading", "MTCond", sizeof(struct __pyx_obj_10ffpyplayer_11ffthreading_MTCond), 1); if (unlikely(!__pyx_ptype_10ffpyplayer_11ffthreading_MTCond)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
> ```
> 
> A way around is to add ffpyplayer in the exclude list, e.g.
> 
> ```
> a = Analysis([...], excludes=['ffpyplayer'])
> ```
> 
> and manually adding the ffpyplayer directory.

Hi, may you give some hints on how to "manually adding the ffpyplayer directory"?
thanks in advance.

**Comment by rnixx** [comment]
You can include missing shared objects manually:

    site_packages = 'venv/lib/python3.7/site-packages'
    a = Analysis(
        ...
        pathex=[site_packages],
        binaries=[
            ('{}/ffpyplayer/*.so'.format(site_packages), 'ffpyplayer'),
            ('{}/ffpyplayer/player/*.so'.format(site_packages), 'ffpyplayer/player')
        ]
        ...
    )

**Comment by matham** [comment]
https://github.com/matham/glitter2/blob/master/packaging/Glitter2.spec#L17 is how I do it.

**Comment by matham** [comment]
Also, pyinstaller now supports entrypoint hooks declared in each project: https://github.com/pyinstaller/pyinstaller/pull/4867 and https://github.com/pyinstaller/hooksample/blob/master/setup.cfg#L32. I'll have to add this at some point in the far future.

**Comment by rnixx** [comment]
@matham Thanks for the update!

**Comment by drodriguezwpb** [comment]
I am packaging my app using pyinstaller, and import ffpyplayer in my code.   pyinstaller builds the executable, but when I execute the program I receive this error:

Traceback (most recent call last):
  File "hdc.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ffpyplayer/player/__init__.py", line 10, in <module>
  File "ffpyplayer/player/player.pyx", line 2, in init ffpyplayer.player.player
ModuleNotFoundError: No module named 'ffpyplayer.threading'
[42447] Failed to execute script hdc

How can I resolve this issue?  Thx.
