### ISSUE TITLE
Using ffpyplayer

### ISSUE THREAD

**Issue by jdauthre** [matham/ffpyplayer#101]
I have installed ffpyplayer on windows 10   including adding path.  Followed all the instructions but get errors when I try to run any examples, eg running simple transcoding example. output:

Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================= RESTART: C:\Users\jdaut\python\ffpyplayer.py =================
Traceback (most recent call last):
  File "C:\Users\jdaut\python\ffpyplayer.py", line 1, in <module>
    from ffpyplayer.player import MediaPlayer
  File "C:\Users\jdaut\python\ffpyplayer.py", line 1, in <module>
    from ffpyplayer.player import MediaPlayer
ModuleNotFoundError: No module named 'ffpyplayer.player'; 'ffpyplayer' is not a package

ffpyplayer is definitely in the site packages folder.  Any clues as to what is going wrong?
Thanks in advance

**Comment by matham** [comment]
It's because your script name, `ffpyplayer.py` is [shadowing](https://mail.python.org/pipermail/python-dev/2015-November/142096.html) the package so Python imports your script instead of the package when you try to import ffpyplayer.

Try renaming your script to something else.

**Comment by jdauthre** [comment]
Thank you!   Should have thought of that
