### ISSUE TITLE
ffpyplayer no video

### ISSUE THREAD

**Issue by jdauthre** [matham/ffpyplayer#102]
Sorry to ask again, I got the  'simple video player' example to run fine, I get the audio but no video  or window . Printing out of the various attributes works fine. I have mucked around with the FFMPEG_ROOT and SDL_ROOT  assuming one or other is not pointing correctly, without success. The code is: 
------------------------------------------------------
from ffpyplayer.player import MediaPlayer
import time
FFMPEG_ROOT="C:/Users/jdaut/python/bin"
SDL_ROOT="C:/Users/jdaut/python"
filename= 'D:/Kingsley Videos/close.mp4'
player = MediaPlayer(filename)
while 1:
    frame, val = player.get_frame()
    if val == 'eof':
        break
    elif frame is None:
        time.sleep(0.01)
    else:
        img, t = frame
        print (val, t, img.get_pixel_format(), img.get_buffer_size())
        time.sleep(val)
--------------------------------------------------------
Thanks in advance

**Comment by matham** [comment]
ffpyplayer does not display the video in any way. It simply returns you the video frames so you can display it with a GUI toolkit e.g. kivy, qt, pygame etc.

**Comment by jdauthre** [comment]
Ah thank you I didn't realise that
