### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by etoilestar** [matham/ffpyplayer#103]
I don't know how to get data from numpy array,can you tell  me?

**Comment by matham** [comment]
Do you mean into numpy arrays? If so, please see https://matham.github.io/ffpyplayer/pic.html#ffpyplayer.pic.Image.to_bytearray and https://matham.github.io/ffpyplayer/pic.html#ffpyplayer.pic.Image.to_memoryview. You can use resulting data to create a numpy array of `np.ubyte` type.
