### ISSUE TITLE
ImportError: DLL load failed while importing player

### ISSUE THREAD

**Issue by gabriellamiles** [matham/ffpyplayer#104]
Hi,

I've downloaded ffpyplayer for Windows 10, having installed it with the command:
    python3 -m pip install ffpyplayer

Simply stating "import ffpyplayer" I get no error, however if I use from, as in:
    from ffpyplayer.player import MediaPlayer

It returns the error:
    ImportError: DLL load failed while importing player: The specified module could not be 
    found.

I've checked the PATH, and it all seems to be fine. Is there any chance you know what is causing this error?

All the best,
Gaby

**Comment by matham** [comment]
Are you using conda? Which version of python? If you're using native python, I'd suggest you create a virtualenv and try from there as probably something else in your env conflicts.

If you're using conda, you need to install it from conda-forge.

**Comment by gabriellamiles** [comment]
Not using conda, Python 3.8 - using Python natively, and did as you suggested (creating a virtualenv) - worked perfectly first time, no issues with the installation/importing at all. Thank you.
