### ISSUE TITLE
MPEG-DASH manifests?

### ISSUE THREAD

**Issue by Twilight0** [matham/ffpyplayer#106]
I don't know if this is the place to ask, but is ffpyplayer to support MPD manifests?

Example: https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

**Comment by matham** [comment]
I haven't tried it, butt ffpyplayer uses ffmpeg under the hood, so if ffmpeg supports it, ffpyplayer supports it. Based on [this answer](https://video.stackexchange.com/a/25389) I checked and the bundled windows ffmpeg supports it. Not sure about other platforms.
