### ISSUE TITLE
FFPyPlayer ffmpeg API

### ISSUE THREAD

**Issue by radiolondra** [matham/ffpyplayer#107]
I need to extract audio from a video.
Using ffmpeg is very simple: `ffmpeg -i <input-video-file> -vn <output-audio-file>`
The same can be simply reached in python with, for example, [this library](https://github.com/kkroening/ffmpeg-python):
```
import ffmpeg
...
ffmpeg.input(self.source).output(self.outfile, format="mp3", **{'vn':None}).run()
```

The problem is that It seems I can't use any other ffmpeg library while I'm using ffpyplayer in kivy, as it doesn't understand anymore which ffmpeg module has to use while playing the video:

```
 Traceback (most recent call last):
   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_86\lib\threading.py", line 926, in _bootstrap_inner
     self.run()
   File "C:/kivy-projects/WeT-OLD/main.py", line 92, in run
     self.callback()
   File "C:/kivy-projects/WeT-OLD/main.py", line 255, in on_info_done
     self.play_video()
   File "C:/kivy-projects/WeT-OLD/main.py", line 284, in play_video
     self.video.play()
   File "C:\kivy-projects\WeT\venv\lib\site-packages\kivy\core\video\video_ffmpeg.py", line 47, in play
     self._player = ffmpeg.FFVideo(self._filename)
 AttributeError: module 'ffmpeg' has no attribute 'FFVideo'
```

Does some ffpyplayer API exist to handle similar ffmpeg commands? (I searched in the docs without any success). This way I could remove [this library](https://github.com/kkroening/ffmpeg-python) and use the ffpyplayer APIs.

**Comment by matham** [comment]
No, but your problem is that kivy is using the ffmpeg video backend, now that it's installed. But that back end is not really maintained anymore.

Instead, you need to set the env variable `KIVY_VIDEO=ffpyplayer` so it uses the right backbend.

**Comment by radiolondra** [comment]
I already did it:
os.environ["KIVY_VIDEO"] = "ffpyplayer"

No success.

**Comment by matham** [comment]
Before importing anything?

Please paste full log.

**Comment by radiolondra** [comment]
[INFO   ] [Logger      ] Record log in C:\Users\Robi\.kivy\logs\kivy_21-04-20_6.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\kivy-projects\WeTube\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\kivy-projects\WeTube\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.2
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 10.18.15.4279'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30 - Build 10.18.15.4279'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Video       ] Provider: ffmpeg
[INFO   ] [Base        ] Start application main loop
Closing...
[INFO   ] [Base        ] Leaving application in progress...

**Comment by radiolondra** [comment]
Now it works. You were right
I was setting the KIVY_VIDEO after some import (not in the head of main.py)
import os
os.environ["KIVY_VIDEO"] = "ffpyplayer"
Now it's the first setting and it works!
Thanks matham!
