### ISSUE TITLE
«'VideoFFPy' object has no attribute '_fbo'» while using with Kivy

### ISSUE THREAD

**Issue by germn** [matham/ffpyplayer#11]
I used same code, config and video as at [this](https://github.com/kivy/kivy/issues/4648) page. `ffpyplayer` was installed instead of `kivy.deps.gstreamer`.

Exception I got:
```
   File "C:\Users\gmn\Dropbox\gmn\code\.virtualenvs\LLP_3.4\lib\site-packages\kivy\core\video\video_ffpyplayer.py", line 205, in _redraw
     self._fbo.ask_update()
 AttributeError: 'VideoFFPy' object has no attribute '_fbo'
```

This is from Kivy log:

```
[INFO              ] [VideoFFPy   ] Using ffpyplayer 4.0.0
[INFO              ] [Video       ] Provider: ffpyplayer(['video_ffmpeg'] ignored)
```

**Comment by matham** [comment]
This is a problem with kivy using ffpyplayer, not ffpyplayer itself. So the issue doesn't belong here. Also, I think may have fixed it with https://github.com/kivy/kivy/commit/b331ac18b2c6a619d7f72f946d339581c1f57e83. 

If you still have the issue after using master containing this fix, please open a issue in kivy.
