### ISSUE TITLE
ImportError in subprocess

### ISSUE THREAD

**Issue by fsneak** [matham/ffpyplayer#110]
Importing MediaPlayer in subprocess will raise ImportError.

My code is simply like this.
```
from multiprocessing import Process


def run():
    from ffpyplayer.player import MediaPlayer
    player = MediaPlayer("1.mp4")
    print("create player", player)


if __name__ == "__main__":
    p = Process(target=run)
    p.start()
    p.join()

```
And it returns
**ImportError: DLL load failed while importing player: The specified module could not be
found.**

It's all OK if I don't use Process and just import MediaPlayer in my main process.
Like this
```
from ffpyplayer.player import MediaPlayer


if __name__ == "__main__":
    player = MediaPlayer("1.mp4")
    print("create player", player)

```
MediaPlayer is imported and created successfully.

Do you have any ideas?

Thank you.

**Comment by matham** [comment]
I'm not sure. If it works fine normally and is only a problem with multiprocessing, then something is probably weird with your environment. Otherwise I have no idea why this would happen.

**Comment by matham** [comment]
Closing as it seems likely a issue with your setup.
