### ISSUE TITLE
ImportError: DLL load failed while importing player

### ISSUE THREAD

**Issue by mkiriejevas** [matham/ffpyplayer#114]
https://github.com/matham/ffpyplayer/issues/104 - the root cause was not found

The root cause of the error is the location of package is installed.

ffpyplayer builds ffmpeg include path as follows:
`_ffmpeg = join(sys.prefix, 'share', 'ffpyplayer', 'ffmpeg', 'bin')`

`sys.prefix` resolves to Python installation directory, e.g. `C:\Program Files\Python`.

If `ffpyplayer` is installed using PIP not in CMD administrator mode, the package is installed into user local `%AppData%\Python` directory. This is the reason ffmpeg does not get resolved as expected.

Solution:
- pip uninstall ffpyplayer
- CMD (Administrator mode)
- pip install ffpyplayer

Solution (preffered):
- Change ffpyplayer to determine ffmpeg shared folder more flexible

**Comment by matham** [comment]
This should be fixed in the next release.
