### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by LEv145** [matham/ffpyplayer#116]
Code:
```py
from ffpyplayer.player import MediaPlayer


test_url = "http://dict.youdao.com/dictvoice?audio=nice&type=1"

player = MediaPlayer(test_url)

while True:
    frame, val = player.get_pts()
    print(frame, val)
```

Error:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
Python:
  - 3.10.1
  - 3.8.9

Ffpyplayer version:
  - 4.3.2
  
Ffmpeg version:
  - n4.4.1

**Comment by matham** [comment]
Hmm I just tried it on windows with latest ffpyplayer and putting time.sleep(5) instead of the loop and it worked fine!

**Comment by matham** [comment]
I would try with ffmpeg 5 and with/without sdl2 mixer.

**Comment by matham** [comment]
Closing, please re-open if the issue occurs with sdl2 mixer installed.
