### ISSUE TITLE
MediaPlayer can not set header when the filename is a http resource

### ISSUE THREAD

**Issue by yumoqing** [matham/ffpyplayer#118]
ENV:
KIVY 2.0.0
python: 3.9.1
ffpyplayer:newest

BUG REPORT
some of the web video resource(http or https protocol) need to set some specific headers, without those headers information, the host will not to response correctly, and then the video will not play.

So, can we have a way to set headers when the filename is a url?

**Comment by matham** [comment]
Take a look here: https://www.jokecamp.com/blog/passing-http-headers-to-ffmpeg/. You need to pass the `headers` arg to the `lib_opts` dict.
