### ISSUE TITLE
error compiling ffpyplayer

### ISSUE THREAD

**Issue by jeffersonchua** [matham/ffpyplayer#12]
pulled the latest ffpyplayer and got this error compiling it ...

```
[ 1/10] Cythonizing ffpyplayer/player/clock.pyx
[ 2/10] Cythonizing ffpyplayer/player/core.pyx
[ 3/10] Cythonizing ffpyplayer/player/decoder.pyx
[ 4/10] Cythonizing ffpyplayer/player/frame_queue.pyx
[ 5/10] Cythonizing ffpyplayer/player/player.pyx
[ 6/10] Cythonizing ffpyplayer/player/queue.pyx
[ 7/10] Cythonizing ffpyplayer/threading.pyx
[ 8/10] Cythonizing ffpyplayer/tools.pyx
[ 9/10] Cythonizing ffpyplayer/pic.pyx
[10/10] Cythonizing ffpyplayer/writer.pyx
building 'ffpyplayer.pic' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11/include -I/v6/src2/ffpyplayer/ffpyplayer/ffpyplayer -I/v6/src2/ffpyplayer/ffpyplayer/ffpyplayer/includes -I/usr/local/include/python2.7 -c ffpyplayer/pic.c -o build/temp.linux-x86_64-2.7/ffpyplayer/pic.o -O3 -fno-strict-aliasing -Wno-error
ffpyplayer/pic.c: In function '__pyx_f_10ffpyplayer_3pic_5Image_to_memoryview':
ffpyplayer/pic.c:7930:52: error: '__pyx_array_type' undeclared (first use in this function)
       __pyx_t_3 = __Pyx_PyObject_Call(((PyObject *)__pyx_array_type), __pyx_emp
                                                    ^
ffpyplayer/pic.c:7930:52: note: each undeclared identifier is reported only once for each function it appears in
ffpyplayer/pic.c:7945:20: error: dereferencing pointer to incomplete type
       __pyx_v_cyarr->data = ((char *)(__pyx_v_self->frame->data[__pyx_v_i]));

ffpyplayer/pic.c:8120:30: error: dereferencing pointer to incomplete type
     __pyx_t_8 = __pyx_v_cyarr->data;
                              ^
ffpyplayer/pic.c: In function '__pyx_pf_10ffpyplayer_3pic_11ImageLoader___cinit__':
ffpyplayer/pic.c:8617:3: warning: 'codec' is deprecated (declared at /usr/include/libavformat/avformat.h:885) [-Wdeprecated-declarations]
   __pyx_t_9 = (__pyx_v_self->format_ctx->streams[0])->codec;
   ^
ffpyplayer/pic.c: In function '__pyx_pf_10ffpyplayer_3pic_11ImageLoader_2__dealloc__':
ffpyplayer/pic.c:9038:9: warning: 'av_free_packet' is deprecated (declared at /usr/include/libavcodec/avcodec.h:4471) [-Wdeprecated-declarations]
         av_free_packet((&__pyx_v_self->pkt));
         ^
ffpyplayer/pic.c: In function '__pyx_f_10ffpyplayer_3pic_11ImageLoader_next_frame':
ffpyplayer/pic.c:9620:9: warning: 'avcodec_decode_video2' is deprecated (declared at /usr/include/libavcodec/avcodec.h:4810) [-Wdeprecated-declarations]
         __pyx_v_ret = avcodec_decode_video2(__pyx_v_self->codec_ctx, __pyx_v_se
         ^
ffpyplayer/pic.c:9763:3: warning: 'av_free_packet' is deprecated (declared at /usr/include/libavcodec/avcodec.h:4471) [-Wdeprecated-declarations]
   av_free_packet((&__pyx_v_self->pkt));
   ^
ffpyplayer/pic.c: In function '__pyx_f_10ffpyplayer_3pic_11ImageLoader_eof_frame':
ffpyplayer/pic.c:10022:9: warning: 'avcodec_decode_video2' is deprecated (declared at /usr/include/libavcodec/avcodec.h:4810) [-Wdeprecated-declarations]
         __pyx_v_ret = avcodec_decode_video2(__pyx_v_self->codec_ctx, __pyx_v_se
         ^
error: command 'gcc' failed with exit status 1
```

My environments ...
# python --version

Python 2.7.12
# cython --version

Cython version 0.25a0
# ffmpeg -version

ffmpeg version 3.0.git Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.9.4 (GCC)
configuration: --enable-nonfree --enable-gpl --enable-avresample --enable-libmp3lame --enable-libx264 --enable-libvpx --disable-videotoolbox --enable-pic --enable-shared --disable-static

**Comment by matham** [comment]
What is the OS? As you can see, it compiled both on [windows ](https://ci.appveyor.com/project/matham/ffpyplayer/branch/master) and [linux ](https://travis-ci.org/matham/ffpyplayer) 5 days ago.

**Comment by jeffersonchua** [comment]
Linux 4.8.0
Python 2.7.12 (default, Aug 21 2016, 22:29:47) 


I upgraded pretty much everything to the latest.

**Comment by matham** [comment]
I reran [travis ](https://github.com/matham/ffpyplayer/blob/master/.travis.yml) and it was all [fine](https://travis-ci.org/matham/ffpyplayer/builds/163509471). So I'm not exactly sure what is going on. The error seems to be a cython thing (which I do update on travis to the latest) related to the [array type](https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/pic.pyx#L828).

Can you maybe try to downgrade cython to e.g. .23 and check if that fixes it?

**Comment by jeffersonchua** [comment]
> Can you maybe try to downgrade cython to e.g. .23 and check if that fixes
it?

Yes, that fixed the problem. Thank you so much!

So, it was the "new" cython (git pulled) that caused the array problem. I
got ffpyplayer to work under kivy with Cython-0.23.tar.gz. And also tried
with Cython-0.24.1.tar.gz and that worked as well. But can't use the latest
cython git version to compile ffpyplayer.

Next I tried Kivy video and trying on 2 files. One played ok, but the
second video encountered alsa buffer underrun and hang not even playing the
video ...

[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.0.1.dev0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil, img_ffpyplayer
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoFFPy   ] Using ffpyplayer 4.0.1.dev0
[INFO   ] [Video       ] Provider: ffpyplayer(['video_gstplayer',
'video_ffmpeg'] ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.1.0-devel
(git-40dd45d)>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 520
(Skylake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
...
ALSA lib pcm.c:8257:(snd_pcm_recover) underrun occurred



If I use the default gstreamer, the video played fine.

[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.0.1.dev0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2,
img_pil, img_ffpyplayer
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [VideoGstplayer] Using Gstreamer 1.9.90.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 12.1.0-devel
(git-40dd45d)>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 520
(Skylake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0


The video came from here ...

    https://www.youtube.com/watch?v=1XEsSRqnOwc

Is there any parameter I can set to solve the underrun issue. Nothing set
in ~/.asoundrc or /etc/asound.conf

Running on Lenovo X260
# cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf1240000 irq 123

# lspci
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 520 (rev
07)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)


Thanks,
Jeff

**Comment by jeffersonchua** [comment]
On Thu, Oct 6, 2016 at 12:39 AM, Jeff Chua <jeff.chua.linux@gmail.com>
wrote:

> Next I tried Kivy video and trying on 2 files. One played ok, but the
> second video encountered alsa buffer underrun and hang not even playing the
> video ...
>


Could be my problem here.

I tried examples/test.py to play the Boeing 737Max mp4 file and it played
fine!

I guess the difference is with using kivy.uix.video Video(), verse test.py
using ffpyplayer.player MediaPlayer() ???


Thanks,
Jeff.

**Comment by matham** [comment]
The original issues was due to this cython issue which has now been fixed in master: https://github.com/cython/cython/issues/1502. 

About ALSA, I rarely use this for audio stuff so I'm not sure. I'm not sure why there would be a difference between them. They should be fairly similar internally. Maybe there are some ffmpeg parameters for controlling buffer size or refresh rates. Not really sure. But you can add filters if you need to. Maybe try with ffplay and see if you have similar issues?

**Comment by jeffersonchua** [comment]
On Fri, Oct 28, 2016 at 12:28 AM, matham <notifications@github.com> wrote:

> The original issues was due to this cython issue which has now been fixed
> in master: cython/cython#1502
> <https://github.com/cython/cython/issues/1502>.
>
Just pull latest cython and confirm fixed.

> About ALSA, I rarely use this for audio stuff so I'm not sure. I'm not
> sure why there would be a difference between them. They should be fairly
> similar internally. Maybe there are some ffmpeg parameters for controlling
> buffer size or refresh rates. Not really sure. But you can add filters if
> you need to. Maybe try with ffplay and see if you have similar issues?
>

Turned out that even with this error, it could still play, so it's not a
show-stopper.

Sorry for the late reply. Thank you.

Jeff.
