### ISSUE TITLE
matham changed ffplayer path

### ISSUE THREAD

**Issue by kalokola** [matham/ffpyplayer#122]

**Comment by kalokola** [comment]
[INFO]:    Downloading ffpyplayer
[INFO]:    -> running mkdir -p /home/kalokola/Deskto...(and 78 more)
[INFO]:    -> directory context /home/kalokola/Desktop/pipie/zipa/.buildozer/android/platform/build-armeabi-v7a/packages/ffpyplayer
[INFO]:    -> running basename https://github.com/mat...(and 32 more)
[INFO]:    -> running rm -f .mark-4.3.4.zip                                    
[INFO]:    Downloading ffpyplayer from https://github.com/matham/ffpyplayer/archive/4.3.4.zip
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)



may @matham include the https://github.com/matham/ffpyplayer/archive/4.3.4.zip file, the file is missing from his github account. compiling kivy apps that needs his package crush on buildozer -v android debug since the download source is empty

**Comment by matham** [comment]
The correct link is https://github.com/matham/ffpyplayer/archive/v4.3.4.zip.
