### ISSUE TITLE
Raw data decoding?

### ISSUE THREAD

**Issue by GoelBiju** [matham/ffpyplayer#13]
Hi,

I have been asking a similar question on other repositories lately and that is if there is a way I could decode raw FLV1 (H.263) video data (from an RTMP source), and decode it into an AVFrame (by maybe providing a AVPacket) and then get the PIL image?

This is something I was looking for on the PyAV repository but that is currently just tailored to handle individual files. I am not sure if this repository is the same.

Thank you.

**Comment by matham** [comment]
It returns Image objects which contain the buffer. See https://matham.github.io/ffpyplayer/examples.html and https://matham.github.io/ffpyplayer/pic.html. It doesn't give you access to low level AVFrames etc (unless you're willing to access the image from cython which does provide access to the underlying AVFrame).

**Comment by GoelBiju** [comment]
Thanks @matham for your help.
