### ISSUE TITLE
Question about compiling for Android

### ISSUE THREAD

**Issue by germn** [matham/ffpyplayer#15]
Currently looks like it's not possible to install ffpyplayer with python-for-android (since ffmpeg recipe is broken and ffpyplayer is not ported for new toolchain) and I'm [trying](https://github.com/kivy/python-for-android/issues/920) to fix it.

Manual says that we need shared FFmpeg and SDL2 libs to compile ffpyplayer. In python-for-android project we have recipes for [ffmpeg](https://github.com/kivy/python-for-android/tree/master/pythonforandroid/recipes/ffmpeg) and [sdl2](https://github.com/kivy/python-for-android/tree/master/pythonforandroid/recipes/sdl2), but both of them compile static libraries instead of shared.

On other hand, recipe for [old toolchain](https://github.com/kivy/python-for-android/blob/old_toolchain/recipes/ffpyplayer/recipe.sh) used existed sdl recipe (with static lib) as dependency. I wounder if you know why it is so. May be old version of ffpyplayer could use static sdl lib?

I also wounder if you have any ideas how to install ffpyplayer with p4a now: am I right that we need new recipes for shared libraries for both ffmpeg and sdl2 (I mean that's no way to use existing ffmpeg/sdl2 static recipes)?

Thanks.

**Comment by matham** [comment]
I have not compiled ffpyplayer for android before so I cannot really help you there. Also, this belongs in the kivy/py4a repos as it's an issue with py4a not ffpyplayer. I'd suggest you ask on IRC or kivy mailing list.
