### ISSUE TITLE
simple transcoding example fails

### ISSUE THREAD

**Issue by Android-for-Python** [matham/ffpyplayer#156]
I'm trying to run the ffpyplayer 'simple transcoding example' https://github.com/matham/ffpyplayer/blob/master/doc/source/examples.rst#simple-transcoding-example
It fails with
```
[mp4 @ 000001f701ac0140] Could not find tag for codec rawvideo in stream #0, codec not currently supported in container
Traceback (most recent call last):
  File "C:\Users\Bobf\Documents\kivy\v\ste.py", line 29, in <module>
    writer = MediaWriter(filename_out, [out_opts])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ffpyplayer\writer.pyx", line 345, in ffpyplayer.writer.MediaWriter.__cinit__
Exception: Error writing header: Invalid argument
```
But I think the the 'rawvideo' codec exists, because this prints `True`:
```
from ffpyplayer.tools import codecs_enc
print('rawvideo' in codecs_enc)
```
Any suggestions?

**Comment by matham** [comment]
The error message indicates that you're trying to use the rawvideo codec with a file type (i.e. container) that does not support this codec. I.e. some containers don't support it (I think `mp4` is one of those). You need to use e.g. the `mkv` container.
