### ISSUE TITLE
No such file or directory: 'ffpyplayer/includes/ffconfig.h'

### ISSUE THREAD

**Issue by viu-simon** [matham/ffpyplayer#24]
When i run the command "pip install ffpyplayer" on OSX i receive the following error. I'm not sure if it's OS related. 
Python: 2.7
Cython: 0.23

There is a similar issue #23 but it didn't helped me...

I hope somebody knows a solution? 

> Collecting ffpyplayer
>   Using cached ffpyplayer-4.0.0.zip
>     Complete output from command python setup.py egg_info:
>     Selecting SDL2 out of (SDL, SDL2)
>     Generating ffconfig.h
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/z7/kz40w76s6fncq63_bbx0mcvc0000gn/T/pip-build-E7ukWu/ffpyplayer/setup.py", line 220, in <module>
>         with open(join('ffpyplayer', 'includes', 'ffconfig.h'), 'w') as f:
>     IOError: [Errno 2] No such file or directory: 'ffpyplayer/includes/ffconfig.h'
>     
> 
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z7/kz40w76s6fncq63_bbx0mcvc0000gn/T/pip-build-E7ukWu/ffpyplayer/
>

**Comment by matham** [comment]
This is fixed in master (try `pip install https://github.com/matham/ffpyplayer/archive/master.zip`). I haven't updated pypi because there hasn't been that many changes.

Let me know if master doesn't fix it.

**Comment by dclee19** [comment]
I have the same problem (((.... The fix (pip install https://github.com/matham/ffpyplayer/archive/master.zip) didn't help me...
ffpyplayer/pic.c:448:34: fatal error: libavdevice/avdevice.h: Нет такого файла или каталога
