### ISSUE TITLE
Error when installing from pip .zip: `IOError: [Errno 2] No such file or directory: 'ffpyplayer/includes/ffconfig.h'`

### ISSUE THREAD

**Issue by gpip** [matham/ffpyplayer#25]
Hi, when trying to install from the .zip provided the following error occurs:

```
$ pip install ffpyplayer
Collecting ffpyplayer
  Downloading ffpyplayer-4.0.0.zip (714kB)
    100% |████████████████████████████████| 716kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Selecting SDL2 out of (SDL, SDL2)
    Generating ffconfig.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/07/2n1y__gd1x7f1q5jy939k8dr0000gn/T/pip-build-u8WkdJ/ffpyplayer/setup.py", line 220, in <module>
        with open(join('ffpyplayer', 'includes', 'ffconfig.h'), 'w') as f:
    IOError: [Errno 2] No such file or directory: 'ffpyplayer/includes/ffconfig.h'
```

**Comment by dclee19** [comment]
Collecting https://github.com/matham/ffpyplayer/archive/master.zip
  Downloading https://github.com/matham/ffpyplayer/archive/master.zip
     / 3.7MB 1.3MB/s
Installing collected packages: ffpyplayer
  Running setup.py install for ffpyplayer ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-NsfT7X-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jqO25W-record/install-record.txt --single-version-externally-managed --compile:
    WARNING: A problem occured while running pkg-config --libs --cflags libavcodec libavdevice libavfilter libavformat libavutil libswscale libswresample libpostproc (code 1)
    
    Package libavdevice was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libavdevice.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libavdevice' found
    Package libavfilter was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libavfilter.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libavfilter' found
    Package libpostproc was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libpostproc.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libpostproc' found
    
    
    Selecting SDL2 out of (SDL, SDL2)
    Generating ffconfig.h
    Generating ffconfig.pxi
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/ffpyplayer
    copying ffpyplayer/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer
    creating build/lib.linux-x86_64-2.7/ffpyplayer/player
    copying ffpyplayer/player/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/player
    creating build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/common.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_write.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_play.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_pic.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    creating build/lib.linux-x86_64-2.7/ffpyplayer/clib
    copying ffpyplayer/clib/misc.h -> build/lib.linux-x86_64-2.7/ffpyplayer/clib
    running build_ext
    cythoning ffpyplayer/pic.pyx to ffpyplayer/pic.c
    building 'ffpyplayer.pic' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/ffpyplayer
    creating build/temp.linux-x86_64-2.7/ffpyplayer/clib
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/SDL2 -I/tmp/pip-NsfT7X-build/ffpyplayer -I/tmp/pip-NsfT7X-build/ffpyplayer/includes -I/usr/include/python2.7 -c ffpyplayer/pic.c -o build/temp.linux-x86_64-2.7/ffpyplayer/pic.o -O3 -fno-strict-aliasing -Wno-error
    ffpyplayer/pic.c:255:34: fatal error: libavdevice/avdevice.h: Нет такого файла или каталога
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-NsfT7X-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jqO25W-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-NsfT7X-build/

**Comment by matham** [comment]
That's because you need to provide ffmpeg and sdl2 on linux as we don't have wheels for those platforms before you can compile ffpyplayer. See https://matham.github.io/ffpyplayer/installation.html#sdl-and-compiling-ffmpeg.

For ubuntu, take a look at the .travis file, which has a complete example of compiling ffmpeg and then ffpyplayer using that ffmpeg.
