### ISSUE TITLE
ffpyplayer crashes after pausing video if compiled with sdl2 mixer.

### ISSUE THREAD

**Issue by germn** [matham/ffpyplayer#28]
Pausing video leads to crash if ffpyplayer compiled with sdl2_mixer.
[Example project](https://pastebin.com/J6aibUwt) - to reproduce open any video and click on it to pause.

I could reproduce it on both Windows (latest whl) and Android. 
Everything works fine if we didn't compile with sdl2 mixer.

**Comment by matham** [comment]
Do you have an error log?

**Comment by germn** [comment]
Crash happens without Python exception: interpreter itself crashes. 
I see "Program stopped working" popup and "Process finished with exit code -1073740791" in PyCharm console.
I don't know how I can get log or debug trace for this situation.

**Comment by matham** [comment]
Yeah, it's a really obvious bug in the audio. Can't believe I missed it.

**Comment by matham** [comment]
You can find a fixed wheel at https://ci.appveyor.com/project/matham/ffpyplayer/build/1.0.143 under the build for your python version, under artifacts.
