### ISSUE TITLE
About player.get_frame()

### ISSUE THREAD

**Issue by tanliwen999** [matham/ffpyplayer#42]
The return object is: ffpyplayer.pic.Image 
hwo to convert it to opencv mat or numpy ? 
I want used opencv3 cv2.imshow("", mat) method to draw.
I trying to used  ffpyplayer.pic.Image .to_bytearray[0],  but failed.

**Comment by fmascarich** [comment]
I'm sure there's a more efficient way of what I'm doing, but I haven't found any other examples, so here's what I came up with:

            cv2.namedWindow(winname, cv2.WINDOW_NORMAL)
            options = {"sync" : "audio", "framedrop" : True}
            self.player = MediaPlayer(self.video_file_list[self.current_video_index].file_name, ff_opts = options)
            while True:
                frame_tuple, real_delay = player.get_frame()
                if real_delay != 'eof' and frame_tuple is not None:
                    (ff_frame, frame_pts) = frame_tuple
                    frame_size = ff_frame.get_size()
                    mem_view = ff_frame.to_memoryview()
                    if mem_view is None:
                        break
                    frame = np.asarray(mem_view)
                    img_frame = np.asarray(frame[0]).copy()
                    img_frame = img_frame.reshape((frame_size[1], frame_size[0], 3), order='C')
                    fixed_frame = img_frame.copy()
                    # convert BGR to RGB
                    fixed_frame[:,:,2] = img_frame[:,:,0]
                    fixed_frame[:,:,0] = img_frame[:,:,2]
                    cv2.imshow(winname, fixed_frame)
                    cv2.waitKey(1)
