### ISSUE TITLE
Crash while playing audio

### ISSUE THREAD

**Issue by pvcraven** [matham/ffpyplayer#46]
With ffpyplayer on Windows 10 Python 3.6, I try running the following program on ogg or wav files:

    from ffpyplayer.player import MediaPlayer
    
    vid = 'arcade/examples/sounds/phaseJump1.ogg'
    player = MediaPlayer(vid)
    val = ''
    
    while val != 'eof':
        frame, val = player.get_frame()
    
    print("Done")

The sound is played, but at the end of the sound python crashes and I get: `Process finished with exit code -1073741819 (0xC0000005)`

**Comment by matham** [comment]
I would need to see the audio file to understand the issue.

**Comment by pvcraven** [comment]
phaseJump1.ogg sound downloadable here:
https://github.com/pvcraven/arcade/tree/master/arcade/examples/sounds

**Comment by matham** [comment]
I can't replicate the crash with master. Also, given that it doesn't have video, I don't think calling `get_frame` is appropriate. It's better to use `get_pts()` to get the current audio time.
