### ISSUE TITLE
How to save a picture of a video?

### ISSUE THREAD

**Issue by ifdandy** [matham/ffpyplayer#49]
How to save a picture of a video?
I didn't find the API to meet my needs.

@matham

**Comment by matham** [comment]
I added an example here: https://matham.github.io/ffpyplayer/examples.html#saving-an-image-to-disk.

**Comment by ifdandy** [comment]
It can not work better!


> Traceback (most recent call last):
  File "D:/wwwroot/wangyou/player.py", line 91, in <module>
    save()
  File "D:/wwwroot/wangyou/player.py", line 80, in save
    img = sws.scale(img)
  File "ffpyplayer\pic.pyx", line 270, in ffpyplayer.pic.SWScale.scale (ffpyplayer\pic.c:4517)
Exception: Source image doesn't match the specified input parameters.
[swscaler @ 093a6e20] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 09528de0] deprecated pixel format used, make sure you did set range correctly
``
[player.txt](https://github.com/matham/ffpyplayer/files/2104613/player.txt)
