### ISSUE TITLE
I can not save image from a live video stream.

### ISSUE THREAD

**Issue by ifdandy** [matham/ffpyplayer#50]
I tried the method of 'https://matham.github.io/ffpyplayer/examples.html#saving-an-image-to-disk'.
----------------------------------
This is my code:  [player.txt](https://github.com/matham/ffpyplayer/files/2108673/player.txt)
----------------------------------
Traceback (most recent call last):
File "D:/wwwroot/wangyou/player.py", line 91, in 
save()
File "D:/wwwroot/wangyou/player.py", line 80, in save
img = sws.scale(img)
File "ffpyplayer\pic.pyx", line 270, in ffpyplayer.pic.SWScale.scale (ffpyplayer\pic.c:4517)
Exception: Source image doesn't match the specified input parameters.
[swscaler @ 093a6e20] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 09528de0] deprecated pixel format used, make sure you did set range correctly

**Comment by matham** [comment]
You need to make sure the pixel format specified for the file matches the image being passed.
