### ISSUE TITLE
Not able to play usb audio

### ISSUE THREAD

**Issue by ybq123** [matham/ffpyplayer#53]
Hello,
I tried to create player to play usb audio like this:
![image](https://user-images.githubusercontent.com/31053593/46189318-9de1f080-c320-11e8-9bf3-b1a93b1a4d46.png)

however,
![image](https://user-images.githubusercontent.com/31053593/46189178-ec42bf80-c31f-11e8-95de-acadeb1276ed.png)

**are there any way to solve？**

**Comment by matham** [comment]
I'm not really sure how to do what you were trying to accomplish.
