### ISSUE TITLE
4.1.0 and master fails to install via pip

### ISSUE THREAD

**Issue by brentpicasso** [matham/ffpyplayer#55]
Tried using Cython 0.28.5 and 0.23.0, fails with the same error message.  Also fails same way on master.

ffpyplayer 4.0.1 installs successfully.

System is Ubuntu 16.04, python 2.7

==============

~$ sudo -H pip install ffpyplayer==4.1.0
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting ffpyplayer==4.1.0
  Using cached https://files.pythonhosted.org/packages/d6/72/827ee3a519128ba6ea6e6714789435eefbadc03eef92d642f858bd64a313/ffpyplayer-4.1.0.tar.gz
Building wheels for collected packages: ffpyplayer
  Running setup.py bdist_wheel for ffpyplayer ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wPy4ro/ffpyplayer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-Jt_Vz9 --python-tag cp27:
  Selecting SDL2 out of (SDL, SDL2)
  Generating ffconfig.h
  Generating ffconfig.pxi
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/ffpyplayer
  copying ffpyplayer/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer
  creating build/lib.linux-x86_64-2.7/ffpyplayer/player
  copying ffpyplayer/player/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/player
  creating build/lib.linux-x86_64-2.7/ffpyplayer/tests
  copying ffpyplayer/tests/common.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
  copying ffpyplayer/tests/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
  copying ffpyplayer/tests/test_play.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
  copying ffpyplayer/tests/test_write.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
  copying ffpyplayer/tests/test_pic.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
  creating build/lib.linux-x86_64-2.7/ffpyplayer/clib
  copying ffpyplayer/clib/misc.h -> build/lib.linux-x86_64-2.7/ffpyplayer/clib
  running build_ext
  cythoning ffpyplayer/pic.pyx to ffpyplayer/pic.c
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      >>> img2 = copy.deepcopy(img)
  '''
  
  __all__ = ('Image', 'SWScale', 'get_image_size', 'ImageLoader')
  
  include "includes/inline_funcs.pxi"
  ^
  ------------------------------------------------------------
  
  ffpyplayer/pic.pyx:57:0: 'includes/inline_funcs.pxi' not found
  
  building 'ffpyplayer.pic' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/ffpyplayer
  creating build/temp.linux-x86_64-2.7/ffpyplayer/clib
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -I/tmp/pip-install-wPy4ro/ffpyplayer/ffpyplayer -I/tmp/pip-install-wPy4ro/ffpyplayer/ffpyplayer/includes -I/usr/include/python2.7 -c ffpyplayer/pic.c -o build/temp.linux-x86_64-2.7/ffpyplayer/pic.o -O3 -fno-strict-aliasing -Wno-error
  ffpyplayer/pic.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
   #error Do not use this file, it is the result of a failed Cython compilation.
    ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ffpyplayer
  Running setup.py clean for ffpyplayer
Failed to build ffpyplayer
Installing collected packages: ffpyplayer
  Found existing installation: ffpyplayer 4.0.1
    Uninstalling ffpyplayer-4.0.1:
      Successfully uninstalled ffpyplayer-4.0.1
  Running setup.py install for ffpyplayer ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wPy4ro/ffpyplayer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-tTvOhj/install-record.txt --single-version-externally-managed --compile:
    Selecting SDL2 out of (SDL, SDL2)
    Generating ffconfig.h
    Generating ffconfig.pxi
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/ffpyplayer
    copying ffpyplayer/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer
    creating build/lib.linux-x86_64-2.7/ffpyplayer/player
    copying ffpyplayer/player/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/player
    creating build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/common.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/__init__.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_play.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_write.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    copying ffpyplayer/tests/test_pic.py -> build/lib.linux-x86_64-2.7/ffpyplayer/tests
    creating build/lib.linux-x86_64-2.7/ffpyplayer/clib
    copying ffpyplayer/clib/misc.h -> build/lib.linux-x86_64-2.7/ffpyplayer/clib
    running build_ext
    cythoning ffpyplayer/pic.pyx to ffpyplayer/pic.c
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        >>> img2 = copy.deepcopy(img)
    '''
    
    __all__ = ('Image', 'SWScale', 'get_image_size', 'ImageLoader')
    
    include "includes/inline_funcs.pxi"
    ^
    ------------------------------------------------------------
    
    ffpyplayer/pic.pyx:57:0: 'includes/inline_funcs.pxi' not found
    
    building 'ffpyplayer.pic' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/ffpyplayer
    creating build/temp.linux-x86_64-2.7/ffpyplayer/clib
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include/SDL2 -I/tmp/pip-install-wPy4ro/ffpyplayer/ffpyplayer -I/tmp/pip-install-wPy4ro/ffpyplayer/ffpyplayer/includes -I/usr/include/python2.7 -c ffpyplayer/pic.c -o build/temp.linux-x86_64-2.7/ffpyplayer/pic.o -O3 -fno-strict-aliasing -Wno-error
    ffpyplayer/pic.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of ffpyplayer
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wPy4ro/ffpyplayer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-tTvOhj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wPy4ro/ffpyplayer/
brent@brent-desktop:~$

**Comment by fmascarich** [comment]
I'm having the same issue. Ubuntu 16.04, on both python 2.7 and 3.4.
It's a brand new Ubuntu installation.

**Comment by kentcr** [comment]
Same issue, fresh install of Kubuntu 18.10
pip 9.0.1, python 2.7

> ffpyplayer/pic.pyx:57:0: 'includes/inline_funcs.pxi' not found

**Comment by robertpro** [comment]
Same ìssue on Fedora 29, Python 3.7, pip 19.0.3, this is weird since I can see that file here https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/includes/inline_funcs.pxi, is this an PATH error?

**Comment by vadimk2016** [comment]
Same on Ubuntu 18.04

**Comment by matham** [comment]
Try installing directly from github by pointing pip to the zip. It should
be fixed on master, but I haven't made a new release so pypi is not fixed.

**Comment by vadimk2016** [comment]
I confirm, after I installed the ffmpeg with the flag `--enabIe-shared` and following guide https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu I was able to install ffpyplayer from pip with command: `pip install https://github.com/matham/ffpyplayer/archive/master.zip
`

**Comment by matham** [comment]
Thanks! BTW, I updated the install docs for the next release - take a look.
For 18.04 the install is much simpler. Except for the pip part, it should
work now as described there.

**Comment by Krakawet** [comment]
I had hard times to complete the setup, but did it :)
After compiling ffmpeg, i had to remove the ".a" files my ffmpeg lib folder to keep only the ".so" files.
