### ISSUE TITLE
play loop never stop

### ISSUE THREAD

**Issue by redstoneleo** [matham/ffpyplayer#56]
the while loop never stops, what should I do if just need to play the audio once ?

```
import time
filename = 'cox.spx
from ffpyplayer.player import MediaPlayer
player = MediaPlayer(filename)

i = 0
while 1:
    i += 1
    print(i)
    frame, val = player.get_frame()
    print('get_frame-----------', frame, val)
    if val == 'eof':
        break
    elif frame is None:
        time.sleep(0.01)
    else:
        img, t = frame
        print(val, t, img.get_pixel_format(), img.get_buffer_size())
        time.sleep(val)
```

**Comment by matham** [comment]
The `if val == 'eof':` condition should break you out after the the audio is done playing once.

**Comment by redstoneleo** [comment]
The if val == 'eof': condition is already in my code.

Tested with
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
wun7 32bit and ffpyplayer-4.3.0

**Comment by matham** [comment]
Oh, if it's audio only, then `get_frame` won't do much as it's meant for when there's video also. I think it's better then to use `get_pts` to watch the progress.
