### ISSUE TITLE
Audio Waveform Data

### ISSUE THREAD

**Issue by sedthh** [matham/ffpyplayer#58]
First of all, thank you very much for this wrapper, I've been trying out multiple audio player python libraries, and none of them worked as intended on 64-bit Windows 10 for MP3 files. As a last resort, I was thinking about writing my own FFPLAY wrapper and calling it as a subprocess, when I came across this gem. 

I would like to know if it was possible to receive the audio data similarly to 

> frame, val = player.get_frame()

I would like to plot the waveform of the MP3 file, but I've found no functions that allow me to get the data to do so. 

Thank you in advance!

**Comment by matham** [comment]
Please see https://github.com/matham/ffpyplayer/issues/52. The short answer is that the code can be modified to do what you want, but the functionality is not currently present.

**Comment by sedthh** [comment]
Thanks for the quick answer man!
