### ISSUE TITLE
Pyinstaller fails to package dlls

### ISSUE THREAD

**Issue by sedthh** [matham/ffpyplayer#59]
I tried to create an executable under 64-bit Windows 10, but it failed to find the DLLs required by ffpyplayer. 
I've downloaded them with the FFMPEG Windows 64-bit distribution (and found SDL2_mixer.dll online at a random site), put them into a folder and declared it as a path to pyinstaller. There were no missing DLL warnings this time, but the executable has failed to run. I've tried manually overwriting the created ffpyplayer folder with the one in site-packages, and tried copy-pasting all the DLLs into its folder (and also the player's folder) together with the FFMPEG and FFPLAY executables. I still get the following error:

> Traceback (most recent call last):
>   File "editor.pyw", line 25, in <module>
>   File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "libs\mp3.py", line 1, in <module>
>   File "c:\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\ffpyplayer\player\__init__.py", line 10, in <module>
> ImportError: DLL load failed: A megadott modul nem található.
> [22824] Failed to execute script editor

Any idea on how to overcome this problem?

The pyinstaller command is simply:

> pyinstaller.exe -c -F -i icon.ico --paths ffmpeg\ --onedir --log-level=DEBUG editor.pyw

**Comment by matham** [comment]
What I do is add `*[Tree(p) for p in ffpyplayer.dep_bins]` to collect. You can see an example at https://github.com/matham/filers2/blob/master/packaging/Filers2.spec.

**Comment by Cheaterman** [comment]
FWIW, the hiddenimports that are actually needed seem to be:
```
        'ffpyplayer.threading',
        'ffpyplayer.player.queue',
        'ffpyplayer.player.frame_queue',
        'ffpyplayer.player.decoder',
        'ffpyplayer.player.clock',
        'ffpyplayer.player.core',
```
(after painstakingly rebuilding 8 times, haha)

Not that anyone should care, really ; I just feel like the more pyinstaller finds on its own, the better.

**Comment by tito** [comment]
I actually did:
```
FFPYPLAYER_PATH = ffpyplayer.__path__[0]

a = Analysis(['main.py'],
             binaries=[
                 (f'{FFPYPLAYER_PATH}\\*.pyd', 'ffpyplayer'),
                 (f'{FFPYPLAYER_PATH}\\player\\*.pyd', 'ffpyplayer/player'),
             ],
...
```
