### ISSUE TITLE
No way to specify video decoder via kivy video source provider settings

### ISSUE THREAD

**Issue by brentpicasso** [matham/ffpyplayer#60]
Related issue: https://github.com/kivy/kivy/issues/6171

We're using ffpyplayer in kivy, and it seems to be selecting the default software h264 decoder in the kivy video provider,  even though we compiled ffmpeg with the specific hardware decoder. 

What would be the best way to pass the preferred vcodec parameter when we set the KIVY_VIDEO environment variable in our app ? 

Perhaps an additional environment variable "FFPYPLAYER_VCODEC" ?

**Comment by matham** [comment]
Can you specify which hardware decoding you're referring to? Is this nvidia?

**Comment by brentpicasso** [comment]
in this case, it's the RPi. It seems to be defaulting to the software decoder; I hacked ffpyplayer to hardcode the h264_mmal decoder (vcodec parameter) and observed the desired effect.

**Comment by matham** [comment]
OK, then this is really a kivy issue and not a ffpyplayer issue because ffpyplayer provides the appropriate configuration options (`vcodec`) that seems to works for you as intended. An environmental variable would not be a

ppropriate for this as it's meant to be passed to init.
