### ISSUE TITLE
ffpyplayer fails to build with buildozer

### ISSUE THREAD

**Issue by brentpicasso** [matham/ffpyplayer#66]
Buildozer is failing to build ffpyplayer:

$ pip show cython
Name: Cython
Version: 0.28.5

I have specified in the buildozer spec a few different versions - v4.1.0 and master

ffpyplayer==v4.1.0, ffpyplayer_codecs

ffpyplayer, ffpyplayer_codecs

Both are failing to build - SDL2 errors:

ffpyplayer/pic.c:570:23: fatal error: SDL_mixer.h: No such file or directory	
 #include "SDL_mixer.h"	
                       ^	
compilation terminated.	
error: command 'arm-linux-androideabi-gcc' failed with exit status 1
[INFO]:    STDERR:

**Comment by matham** [comment]
This issue really belongs in py4a, or maybe buildozer repo because it's likely an issue with the recipe or something. I also don't use py4a so I cannot debug it anyway.

**Comment by brentpicasso** [comment]
Ok, I will focus there. Thank you.
