### ISSUE TITLE
App crashes on iPhone simulator with ffpyplayer error

### ISSUE THREAD

**Issue by Jessye-Point** [matham/ffpyplayer#67]
Kivy/Python program runs fine on Mac. Created an Xcode project with Kivy-ios toolchain. App runs fine on iPhone simulator, but when audio button is pushed, it crashes. Here is some simplified code which results in the same crash. This is the error Xcode gives after the app crashes on the iPhone simulator:

```
File "ffpyplayer/player.pyx", line 203, in 
ffpyplayer.player.MediaPlayer.__cinit__   TypeError: __cinit__()
takes at least 2 positional arguments (1 given)
```

```
import os

os.environ['KIVY_AUDIO'] = 'ffpyplayer'
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.gridlayout import GridLayout
from ffpyplayer.player import MediaPlayer

import kivy, time

class MainScreen(GridLayout):
    def __init__(self, **kwargs):
        super(MainScreen, self).__init__(**kwargs)
        self.cols = 2
        self.row = 1
        self.hello = Button(text="play the audio")
        self.hello.bind(on_press=self.playit)
        self.add_widget(self.hello)

    def playit(self, *args):
        audiofiletoload = "hours.ogg"
        self.newplayer = MediaPlayer(audiofiletoload)
        time.sleep(0.1)
        self.newplayer.seek(30, relative=False, accurate=False)
        time.sleep(2.0)
        self.newplayer.close_player()

class MyApp(App):
    def build(self):
        return MainScreen()

if __name__ == '__main__':
    MyApp().run()
```

**Comment by matham** [comment]
You seem to be using a very old version of ffpyplayer. Please update to the last release or master and that should fix it.

**Comment by Jessye-Point** [comment]
Thank you.  I see I'm running ffpyplayer 4.2.0dev0 when I execute on the Mac.  However, inside the kivy-ios folder, the ffpyplayer recipes is v3.2.  Probably a silly question, but how do you update the recipe?

**Comment by matham** [comment]
I'm not sure as I don't use kivy-ios. You should check on the kivy-ios repo. You can also try asking on the kivy discord channel.
