### ISSUE TITLE
Can't play audio stream on Android

### ISSUE THREAD

**Issue by Cheaterman** [matham/ffpyplayer#72]
Hi Matham, I hope you're doing good :-)

I'm trying to play my webradio https://tms-server.com/radio.ogg on Android, which freezes my application for a good while, and then I get this:

```
I/AEE/AED (15507): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/AEE/AED (15507): Build fingerprint: 'alps/full_n316b/n316b:5.1/LMY47D/1446172618:user/test-keys'
I/AEE/AED (15507): Revision: '0'
I/AEE/AED (15507): ABI: 'arm'
I/AEE/AED (15507): pid: 15353, tid: 15386, name: SDLThread  >>> org.cheaterman.tmsapp <<<
I/AEE/AED (15507): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
I/AEE/AED (15507):     r0 00000000  r1 00000000  r2 00000001  r3 a2691018
I/AEE/AED (15507):     r4 00000080  r5 9fdbf318  r6 9fb65e40  r7 a2d9ddf8
I/AEE/AED (15507):     r8 a07404a4  r9 00000008  sl 00000000  fp a2d9de40
I/AEE/AED (15507):     ip a073be18  sp a2d9dde8  lr a07277db  pc a3fe689c  cpsr 200f0030
I/AEE/AED (15507): 
I/AEE/AED (15507): backtrace:
I/AEE/AED (15507):     #00 pc 0000889c  /data/app/org.cheaterman.tmsapp-1/lib/arm/libSDL2_mixer.so (Mix_Volume+39)
I/AEE/AED (15507):     #01 pc 000097d7  /data/data/org.cheaterman.tmsapp/files/app/_python_bundle/site-packages/ffpyplayer/player/player.so
```

Thanks in advance if you have ideas - I'll try to poke at it myself too.

**Comment by Cheaterman** [comment]
Turns out that's not the "big" issue - the "big" issue is within Kivy: https://github.com/kivy/kivy/pull/6461

**Comment by Cheaterman** [comment]
Trying to rebuild without `USE_SDL2_MIXER` in the environment by editing the recipe seems to be what fixed the OP issue, by the way. The "big" issue that was mentioned here merely freezes the app for about 10 seconds.

**Comment by matham** [comment]
So this was resolved and can be closed? It doesn't seem to be an issue with ffpyplayer directly?

**Comment by Cheaterman** [comment]
It's been a while, bud... I don't quite remember. I think the biggest
issues were in Kivy and/or arm64 builds (possibly the recipe?) but my app
works now. I guess we can close this!
