### ISSUE TITLE
Error calling SWScale using Visual Studio Code

### ISSUE THREAD

**Issue by donquibeats** [matham/ffpyplayer#73]
Hello

I'm a newbie, using Visual Studio Code to try to get a little ffpyplayer movie player together in the hope of using it in a more advanced way going forward.

Partly based on the code from https://matham.github.io/ffpyplayer/examples.html#saving-an-image-to-disk , I've got a media player instance running, and I can hear the audio playing from the file- but getting an image out of it is causing me problems.

The chunk of my code is below- it's just a prototype, aiming to get just one image out of the file, but when it hits the last line, `img2 = sws.scale(img)`, it's throwing this unusual error:
`Unable to open pic.pyx: Unable to read file (Error: File not found (c:\users\[...]\documents\pythontests\ffpyplayer\pic.pyx))`

I'm not sure why it would be looking in the project's path for this ffpyplayer file? Might this be a config issue, or a bug? I'm new to Python so I fear I may be misdiagnosing the problem.

All the libraries I've installed have been through pip install etc.

Any help or pointers would be appreciated, if this isn't a bug.

Thanks

Stuart

`player = MediaPlayer(filename)
    val = ''
    while val != 'eof':
        frame, val = player.get_frame()
        if val != 'eof' and frame is not None:
            img, t = frame
            pictureBox = tk.Tk()
            w = 640
            h = 360
            sws = SWScale(w, h, img.get_pixel_format(), w, h)
            img2 = sws.scale(img)`

**Comment by matham** [comment]
I'm not sure. I'm guessing you also named your project ffpyplayer and python gets confused between the two projects. Otherwise, it's probably something about the installation that I can't really do much about unless you have something reproducible.

Please feel free to re-open if you have a reproducible example.
