### ISSUE TITLE
request_channel cordump

### ISSUE THREAD

**Issue by yumoqing** [matham/ffpyplayer#75]
This is code 
```
from ffpyplayer.player import MediaPlayer
mp = MediaPlayer('./a.mp4')
mp.request_channel('audio' ,action='open',requested_stream=-1)
mp.close_player()
```
when it run, it coredump

the "a.mp4" video file has two audio tracks

**Comment by matham** [comment]
You probably need to wait until the file is playing before you can call that.

**Comment by yumoqing** [comment]
Yes, it work, after mp_get_frame() return frame and val.
Thanks a lot

**Comment by yumoqing** [comment]
Are there function to query audio tracks info in ffpyplayer?发自我的华为手机-------- 原始邮件 --------发件人： matham <notifications@github.com>日期： 2019年9月4日周三 半夜12:45收件人： matham/ffpyplayer <ffpyplayer@noreply.github.com>抄送： yumoqing <yumoqing@gmail.com>, Author <author@noreply.github.com>主    题： Re: [matham/ffpyplayer] request_channel cordump (#75)You probably need to wait until the file is playing before you can call that.

**Comment by matham** [comment]
I don't believe so.
