### ISSUE TITLE
Raspberry Pi 4B, Kivy Video class and ffpyplayer freezing up

### ISSUE THREAD

**Issue by OutsourcedGuru** [matham/ffpyplayer#81]
I could have sworn that I tested this earlier and that it was working as expected. Today, though, I'm seeing that attempting to bring up a Kivy Video using the ffpyplayer provider on this platform is silently crashing the app. It goes unresponsive, probably blocks the main Python thread in doing so. The only thing I see in the log is:

```
2019-12-09 11:02:56,523 - kivy - ERROR - Image: Error reading file http://localhost:8080/?action=stream
```

This link of course is the output from the `mjpg_streamer` service.

- Raspberry Pi 4B (4GB)
- Raspbian Buster Lite
- OctoPi 0.17.0 IMG with OctoPrint 1.3.12
- **ffpyplayer** 4.3.1.dev0
- Kivy 1.10.1
- Python 2.7
- nodm 0.13 with xserver-xorg installed
- mjpg_streamer git rev 501f6362c5afddcfb41055f97ae484252c85c912
- Pi NoIR webcam v2 provided by Adafruit

## Installation method:
```
source ~/oprint/bin/activate
pip install pygments docutils Cython==0.28.2 wheel
sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev python-setuptools libgstreamer1.0-dev git-core gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} python-dev libmtdev-dev xclip xsel
sudo apt-get install -y  ffmpeg libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev libpostproc-dev libsdl2-dev libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-mixer-dev python3-dev
pip install https://github.com/matham/ffpyplayer/archive/master.zip
```

## Smaller test

**testcam.py:**
```
import os
os.environ['KIVY_WINDOW'] =                 'sdl2'
os.environ['KIVY_GL_BACKEND'] =             'gl'
os.environ['KIVY_VIDEO'] =                  'ffpyplayer'
from kivy.app import App
from kivy.core.window                       import Window
from kivy.uix.video                         import Video
Window.fullscreen =                         True

class KivyVideo(App):
    def build(self):
        return Video(state="play", source="http://localhost:8080/?action=stream")

KivyVideo().run()
```

**\.xsession**
```
#!/bin/bash
export DISPLAY=:0.0
/usr/bin/xset s off
/usr/bin/xset -dpms
/usr/bin/xset s noblank
source /home/pi/oprint/bin/activate
#octoprint serve
python /home/pi/tmp/testcam.py
```

**Run:**
```
sudo service nodm start
```

I can visit the bare link http://octopi.local:8080/?action=stream and it produces a nice webcam stream back via the browser. So I know the ribbon cable to the webcam is good and that the service is streaming to this port.

Commenting out the line `os.environ['KIVY_VIDEO'] = 'ffpyplayer'` in the Kivy test file falls back to `gstplayer` and works (sluggishly). I replaced that player perhaps six months ago when I noticed that it had a pretty bad memory leak.

**Comment by matham** [comment]
This is a problem with kivy's usage of ffpyplayer - it does indeed block the main thread for a bit while kivy is trying to read the stream metadata through ffpyplayer. Perhaps that times out and metadata is never able to be read.

But this is not a issue with ffpyplayer itself, so this belongs with kivy. Please re-open the issue in kivy, if you have a reproducible example. But I doubt we could do anything there, unless you figure out what exactly is causing it as it may be stream specific.

**Comment by matthiasharrer** [comment]
Hey, I was also running into this issue and tried to dig a little bit further. From the kivy side it seems to freeze exactly here: https://github.com/kivy/kivy/blob/master/kivy/core/video/video_ffpyplayer.py#L346 which to me looks like it's not a problem in kivy is it?

I am trying to run this on a raspberry pi 4 with raspian buster and the ffmpeg from the raspian package sources. (ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers).

Is there a way to get more debug output from ffpyplayer? I already tried calling `ffpyplayer.tools.set_loglevel` but I couldn't see any logs from ffpyplayer (assuming the logs are correctly handled by the kivy logger).

Thanks a lot for your help!

**Comment by matthiasharrer** [comment]
Here is a minimal example that still freezes when pressing the button (on raspian):

```
import logging

from kivy.app import App
from kivy.logger import Logger
from kivy.uix.button import Button

import ffpyplayer
from ffpyplayer.player import MediaPlayer

Logger.setLevel(logging.TRACE)


class TestApp(App):

    def callback(self, *args, **kwargs):
        pass

    def click(self, *args, **kwargs):

        def callback(*args, **kwargs):
            print('callback')

        ff_opts = {'paused': False, 'out_fmt': 'rgba', 'sn': True, 'volume': 1.0}

        print('still here')
        MediaPlayer('/home/pi/small.mp4', callback=self.callback, thread_lib='SDL', loglevel='trace', ff_opts=ff_opts)

    def build(self):
        button = Button(text='Click & Freeze')
        button.bind(on_press=self.click)

        return button


TestApp().run()

```

**Comment by matthiasharrer** [comment]
It seems to work back in Kivy 1.10.1 with Python 2.7 so it indeed seems to be a Kivy issue .. but a very weird one
