### ISSUE TITLE
Raspberry Pi WARNINGs and ERRORs need tuneup?

### ISSUE THREAD

**Issue by frankgould** [matham/ffpyplayer#82]
My app is streaming video using `ffpyplayer` fine displayed through `kivy` on Arch Linux ARM 4.19; however, I get a ton of WARNINGs and ERRORs in my log, as I pasted below that is from the attached log file. I don't know where to start looking for parameters I need to tweak to set it to work with fewer log alerts. Before, my app used `gstreamer` and it never had these alerts.

My video streaming configuration uses `picam` and `node-rtsp-rtmp-server` with details at the links below. If someone can point me in the right direction, I'll set the parameters to test. Any and all suggestions are appreciated.

https://github.com/iizukanao/node-rtsp-rtmp-server
https://github.com/iizukanao/picam
```
[WARNING] ffpyplayer: [rtsp @ 0x6a500660] max delay reached. need to consume packet
[WARNING] ffpyplayer: [rtsp @ 0x6a500660] RTP: missed 2 packets
[ERROR  ] ffpyplayer: [h264 @ 0x699a51d0] out of range intra chroma pred mode
[ERROR  ] ffpyplayer: [h264 @ 0x699a51d0] error while decoding MB 22 44
[WARNING] ffpyplayer: [rtsp @ 0x6a500660] max delay reached. need to consume packet
[WARNING] ffpyplayer: [rtsp @ 0x6a500660] RTP: missed 2 packets
[ERROR  ] ffpyplayer: [h264 @ 0x6999a810] corrupted macroblock 11 32 (total_coeff=-1)
[ERROR  ] ffpyplayer: [h264 @ 0x6999a810] error while decoding MB 11 32

```
[remote-log-19-12-20_2.txt](https://github.com/matham/ffpyplayer/files/3988827/remote-log-19-12-20_2.txt)

**Comment by matham** [comment]
This is coming from ffmpeg directly and not from ffpyplayer. This is either an issue with the stream or with the version of ffmpeg available on the Pi. But, you should look into perhaps optimizing any off the ff_opts passed to ffmpeg. Try playing the stream with ffplay and find the right delay parameters etc. and then use that for ffpyplayer.
