### ISSUE TITLE
Symbol not found: _objc_alloc_init 

### ISSUE THREAD

**Issue by zh794390558** [matham/ffpyplayer#87]
os: macOS
```
Traceback (most recent call last):
  File "ffplay.py", line 2, in <module>
    from ffpyplayer.player import MediaPlayer
  File "/usr/local/lib/python3.7/site-packages/ffpyplayer/player/__init__.py", line 10, in <module>
    from ffpyplayer.player.player import MediaPlayer
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/ffpyplayer/player/player.cpython-37m-darwin.so, 2): Symbol not found: _objc_alloc_init
  Referenced from: /usr/local/lib/python3.7/site-packages/ffpyplayer/player/../.dylibs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /usr/local/lib/python3.7/site-packages/ffpyplayer/player/../.dylibs/libSDL2-2.0.0.dylib
```

**Comment by mistvfx** [comment]
you found any solutions ?

**Comment by wasimafser** [comment]
you found any solutions ??

>  Referenced from: /usr/local/lib/python3.7/site-packages/ffpyplayer/player/../.dylibs/libSDL2-2.0.0.dylib (which was built for Mac OS X 10.15)

this seems like a recent update to fix something has messed up with the libs ?

**Comment by matham** [comment]
I'd suggest that you install ffpyplayer from master by following https://matham.github.io/ffpyplayer/installation.html#compiling. I'm guessing something is broken with the included binaries, but I can't really debug this as I'm not very familiar with osx.

**Comment by matham** [comment]
The GitHub actions CI runs on OSX 10.15. This unfortunately means it won't work for older versions of OSX. There's not much we can do unless they start supporting offering older OSX versions.

So as suggested, the best solution is to compile ffpyplayer on your machine.
