### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gitMesa** [matham/ffpyplayer#89]
Hey,

This is more as feedback instead of an actual issue.

I've tried for a whole day to use this library because it seems a lot less verbose then most of the video processing libraries out there. It seemed very easy to use. And the last update was relatively recent (2020-02-26 as of this post), so it seemed like a really maintained library.

But after trying to figure it out for N hours, i got stuck at actually using the frames loaded by this library.

I use pyqtgraph which is extremely fast, but this is pretty irrelevant.
The problem came from trying to connect ffpyplayers output frames to the input format that pyqtgraph needs. It needs some kind of numpy array which is pretty badly defined from their part as well i think.

Anyway after searching for hours online for ANY examples on how to export numpy arrays at all from ffpyplayer, the only "example" i found was actually in issues, asked in 2017.
https://github.com/matham/ffpyplayer/issues/42

Now to my point. 
The documentation is either really incomplete, or doesn't fully explain the power in this library.
And that, in my opinion, turns into less examples (ex, stackoverflow topics) which could help the users of this library find solutions for their issues.

I know you cannot cover ALL kind of image display options that are out there, but at least with numpy it seemed very used, and there were little to none examples out there.

Please consider HOW people use this library, and consider providing some examples on HOW to achieve those.

For example:
How to extract frame by frame and play frame by frame in different formats.
How to display frames in common formats (numpy RGB arrays).
How to link timestamps to the frames.

Anyway this is just some frustration I've had with this library, but i'm moving over to another one because it seems to have better documentation / examples on stackoverflow.

Hopefully you take this as a suggestion instead of a complaint.

Have a great day :)

**Comment by matham** [comment]
I appreciate your feedback, but I'm the only one "maintaining" the library hence the basic documentation. That being said, there's pretty clear documentation for how to access the raw data from the images: there are both [memeoryviews](https://matham.github.io/ffpyplayer/pic.html#ffpyplayer.pic.Image.to_memoryview) and [bytes](https://matham.github.io/ffpyplayer/pic.html#ffpyplayer.pic.Image.to_bytearray) getters.

Once you have these bytes or memoryviews it should be trivial to create a numpy array from them, simply create a numpy array from the data (`np.asarray`) and then add a dimension and reshape it to the width x height.
