### ISSUE TITLE
Markdown syntax at installation documentation page

### ISSUE THREAD

**Issue by jeroenpeters1986** [matham/ffpyplayer#9]
Little styling issue in: we need the shared version. This means that --enable-shared and --extra-cflags="-fPIC"` need to be added when compiling FFmpeg **AND** its dependencies. And if present, ``--disable-shared or --enable-static must be removed.

**Comment by matham** [comment]
You made a pull request to your own fork. Can you please make one to ffpyplayer?

**Comment by jeroenpeters1986** [comment]
Just did, I always get mixed up... Sorry!
