### ISSUE TITLE
Import Error on Raspberry Pi

### ISSUE THREAD

**Issue by ash80** [matham/ffpyplayer#91]
from ffpyplayer.player import MediaPlayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ffpyplayer/player/__init__.py", line 10, in <module>
    from ffpyplayer.player.player import MediaPlayer
ImportError: /usr/local/lib/python3.5/dist-packages/ffpyplayer/player/player.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: x264_levels

**Comment by BackMountainDevil** [comment]
Excuse me. Could you please write somme about how you install it?

**Comment by matham** [comment]
Seems like something is wrong with your system or ffpyplayer doesn't support your particular OS that you installed on the pi.
