### ISSUE TITLE
Frozen Baseline is Crashing on “from ffpyplayer.player import MediaPlayer”

### ISSUE THREAD

**Issue by slalomchip** [matham/ffpyplayer#93]
I using Python 3.8 on a Windows 10 platform.  I have a frozen script that plays video without any issue (not using fypyplayer).  I added audio via ffpyplayer to it in the development environment (Spyder) using the package ffpyplayer.  It worked great.  Then I froze the new baseline and it crashes on the line from “ffpyplayer.player import MediaPlayer”

I have tried different things to fix the issue:
1.	In the pyinstaller spec file, I excluded ffpyplayer and then added the entire ffpyplayer folder found in the Python site-packages folder to the distribution folder that was built by pyinstaller
2.	I used this suggestion [https://github.com/matham/ffpyplayer/issues/59] and included hooks for 'ffpyplayer.threading', 'ffpyplayer.player.queue', 'ffpyplayer.player.frame_queue',  'ffpyplayer.player.decoder', 'ffpyplayer.player.clock', 'ffpyplayer.player.core'.  This seems to be a subset of adding the entire folder from site-packages
Neither of these worked.  

I tried it last year using cx_Freeze and finally gave up.  Is there any recommended solution to get ffpyplayer successfully imported into a frozen baseline?

**Comment by matham** [comment]
The contents of the [sdl](https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/__init__.py#L41) and [ffmpeg](https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/__init__.py#L34) need to be copied to your frozen installation and added to the `PATH`. 

You can find the full list of paths whose contents need to be copied in https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/__init__.py#L27 (`dep_bins`). That's where the binaries required to run ffpyplayer are stored on windows.
