### ISSUE TITLE
Reacting on errors happening while (trying to) playback video

### ISSUE THREAD

**Issue by rnixx** [matham/ffpyplayer#96]
Is there a supposed way to react on error happening while video loading/playback?

See https://github.com/kivy/kivy/issues/7068

**Comment by matham** [comment]
ffpyplayer supports a error callback to be passed when you construct the player object. This will be called with any errors: https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/player/player.pyx#L75.

Kivy does not really implement that, I believe, but that's a issue on the kivy side as there's no clear API for kivy to raise such an error.
