### ISSUE TITLE
p4a: compile against non GPL ffmpeg version

### ISSUE THREAD

**Issue by rnixx** [matham/ffpyplayer#99]
I try to compile ffpyplayer against non GPL ffmpeg with p4a. I use version n4.3.1 of ffmpeg and v4.3.1 of ffpyplayer.

ffpyplayer build fails during p4a run due to missing ``postprocess.h``, which is not included in built when compiling ffmpeg without GPL components.

>   In file included from ffpyplayer/pic.c:653:	
    ffpyplayer/clib/misc.h:18:10: fatal error: 'libpostproc/postprocess.h' file not	
          found	
    #include "libpostproc/postprocess.h"	
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Any ideas?

**Comment by rnixx** [comment]
looks like CONFIG_POSTPROC is defined somehow.

https://github.com/matham/ffpyplayer/blob/master/ffpyplayer/clib/misc.h#L17

**Comment by matham** [comment]
Yeah, here: https://github.com/matham/ffpyplayer/blob/master/setup.py#L54.

Just export `CONFIG_POSTPROC=0` and see if that fixes it.

**Comment by rnixx** [comment]
After setting CONFIG_POSTPROC=0 in the ffpyplayer recipe the compiler not complains any more, but now the linker fails with

  > aarch64-linux-android/bin/ld: cannot find -lpostproc	
clang: error: linker command failed with exit code 1

I tried to exclude from libraries here https://github.com/matham/ffpyplayer/compare/master...rnixx:disable_postproc?expand=1 but it has no effect.

Where are the libraries to link defined?

**Comment by matham** [comment]
Hmm, your changes should have disabled it. Can you post the complete command log? It should show who's trying to link.

**Comment by rnixx** [comment]
Sorry for the noise, just built the whole thing from scratch and it works \o/
